// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("tracesimulationreceiver")
	ScopeName = "github.com/k4ji/tracesimulationreceiver"
)

const (
	TracesStability = component.StabilityLevelAlpha
)
